services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
      CHROMADB_MODE: http
      CHROMADB_HOST: chromadb
      CHROMADB_PORT: 8000
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis
      - postgres
    ports:
      - "8002:8000"

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
      CHROMADB_MODE: http
      CHROMADB_HOST: chromadb
      CHROMADB_PORT: 8000
    command: celery -A backend.tasks.celery_app.celery_app worker -l info
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: studyagent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  chromadb:
    image: chromadb/chroma:1.0.20
    volumes:
      - chromadata:/chroma/chroma

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

  prometheus:
    image: prom/prometheus:v3.5.0
    depends_on:
      - backend
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:12.2.0
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafanadata:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  pgdata:
  chromadata:
  grafanadata:
